# Generated by Django 4.2.2 on 2023-07-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password_plaintext',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
