# Generated by Django 4.2.2 on 2023-07-30 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_password_plaintext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password_plaintext',
        ),
    ]
